### ISSUE TITLE
Training SAEs for Chat Models

### ISSUE THREAD

**Issue by Hambaobao** [EleutherAI/sae#21]
Hello, 

Thanks for your great work.
I’ve noticed that everyone is using activations from Base models to train SAEs. Therefore, I would like to ask, for a Chat model, if I want to train a corresponding SAE, what kind of data should I use? While Base models use normal text snippets, is it necessary for Chat models to use instruction data for training?

Best regards,

**Comment by norabelrose** [comment]
This is a good question. I think it is important to train the SAE on a lot of pretraining-style data in order to capture what the model learned during pretraining. The ideal approach may be to first train the SAE on the base model with pretraining data, then finetune it on the chat model with chat data, or something.

**Comment by Hambaobao** [comment]
Thank you for your reply. I will try it.
